require("dotenv").config();

module.exports = {
  env: process.env.NODE_ENV,
  port: process.env.PORT,
  jwt: {
    secret: process.env.JWT_SECRET,
    accessExpirationMinutes: process.env.JWT_EXPIRATION_MINUTES,
  },
  mongo: {
    uri:
      process.env.NODE_ENV === "test"
        ? process.env.TEST_DATABASE_URL
        : process.env.DATABASE_URL,
  },
  emailConfig: {
    host: process.env.EMAIL_HOST,
    port: process.env.EMAIL_PORT,
    username: process.env.EMAIL_USERNAME,
    password: process.env.EMAIL_PASSWORD,
  },
  mssql: {
    server: process.env.SQL_SERVER,
    database: process.env.SQL_DATABASE,
    user: process.env.SQL_USER,
    password: process.env.SQL_PASSWORD,
    options: {
      encrypt: process.env.SQL_ENCRYPT === "true",
    },
  },
  FIORANO: process.env.FIORANO_URL,
  ICOIN_STERLING_ACCT: process.env.ICOIN_STERLING_ACCT,
  interBankTransfer: {
    user: process.env.SQL_USER,
    server: process.env.SQL_SERVER,
    db: process.env.SQL_DATABASE,
    password: process.env.SQL_PASSWORD,
  },
  AES_DB_KEY: process.env.AES_DB_KEY,
  AES_DB_IV: process.env.AES_DB_IV,
  MONGO_HOST: process.env.MONGO_HOST,
  MONGO_PORT: process.env.MONGO_PORT,
  MONGO_DB_NAME: process.env.MONGO_DB_NAME,
  AES_REQ_RES_KEY: process.env.AES_REQ_RES_KEY,
  AES_REQ_RES_IV: process.env.AES_REQ_RES_IV,
  NAME_ENQUIRY_URL: process.env.NAME_ENQUIRY_URL,
  FLUTTERWAVE_PUBLIC_KEY: process.env.FLUTTERWAVE_PUBLIC_KEY,
  FLUTTERWAVE_SECRET_KEY: process.env.FLUTTERWAVE_SECRET_KEY,
  FLUTTERWAVE_ENCRYPTION_KEY: process.env.FLUTTERWAVE_ENCRYPTION_KEY,
  FLUTTERWAVE_API: process.env.FLUTTERWAVE_API,
  EWSERVICE_URL: process.env.EWSERVICE_URL,
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_A,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_IDPP_ID,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
  APP_NAME: process.env.NAME,
  STERLLAR_SERVER_URL: process.env.STERLLAR_SERVER_URL,
  NETWORK_PASSPHRASE: process.env.NETWORK_PASSPHRASE,
  
  APP_MNEMONIC: process.env.APP_MNEMONIC,
  ONE_WALLET_KEY: process.env.ONE_WALLET_KEY,
  ONE_WALLET_IV: process.env.ONE_WALLET_IV,
  ONE_WALLET_API: process.env.ONE_WALLET_API,
  ONE_WALLET_CHANNEL_ID: process.env.ONE_WALLET_CHANNEL_ID,
  ONE_WALLET_PRODUCT_ID: process.env.ONE_WALLET_PRODUCT_ID,
  ONE_WALLET_POOL: process.env.ONE_WALLET_POOL,
  ONE_WALLET_ICOIN_ACCT: process.env.ONE_WALLET_ICOIN_ACCT,
  ONE_WALLET_ALGORITHM: process.env.ONE_WALLET_ALGORITHM,
  AD_SERVICE_URL: process.env.AD_SERVICE_URL,
  ICOIN_DASHBOARD_URL: process.env.ICOIN_DASHBOARD_URL,
  AMQP_URL: process.env.AMQP_URL,
  CREATE_VIRTUAL_ACCOUNT_CRON: "0 0 */12 * *",
  CALCULATE_ASSETS_IN_CIRCULATION_CRON: "0 0 */12 * *",
  CLOSE_TRADE: "0 0 */12 * *",
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_TLS: true,
  DB_ENCRYPTION_ALGORITHM: process.env.DB_ENCRYPTION_ALGORITHM,
  RESPONSE_ENCRYPTION_ALGORITHM: process.env.RESPONSE_ENCRYPTION_ALGORITHM,
  AZURE_CONNECTION_STRING: process.env.AZURE_CONNECTION_STRING,
  AZURE_BLOB_BASE_URL: process.env.AZURE_BLOB_BASE_URL,
  ERROR_MESSAGE: process.env.ERROR_MESSAGE,
  MTOKEN_SERVICE_HASHKEY: process.env.MTOKEN_SERVICE_HASHKEY,
  MTOKEN_SERVICE_URL: process.env.MTOKEN_SERVICE_URL,
  UseMToken: process.env.UseMToken,
  SUPER_LOGIN: process.env.SUPER_LOGIN,
  CENTRAL_ISSUE_POINT: process.env.CENTRAL_ISSUE_POINT,
  SALT: process.env.SALT,
  EMAIL_SENDER: process.env.EMAIL_SENDER,
};
